#pragma config(Sensor, dgtl1,  driveSensor,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  armSensor,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  driveLeftSensor, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  greenLED1,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  greenLED2,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  redLED1,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, redLED2,        sensorLEDtoVCC)
#pragma config(Motor,  port1,           mobileL,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           driveL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveR,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           armL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           armR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           wristL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           wristR,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           clawL,         tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           clawR,         tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mobileR,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, in1,    clawPotato,     sensorPotentiometer)
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "definesVariables.h"
#include "functions.h"


void pre_auton()
{

	bStopTasksBetweenModes = true;

}



task autonomous()
{

	stopDrivingClearSensor(); // The reason I wrote, this autonomuos code was
														// to compliment the code of other high-level
	claw = -127;							// teams, rather than simply show off my abilities.
	delay(500);								// This way, while our autonomous isn't as high scoring
														// as others, this way we have a better chance
	claw = 0;									// of winning by synergizing with other teams with
	armMotors = 127;					// high scoring autonomus periods. Focusing on benefit
	wrist = 70;								// rather than showing personal skill.
	delay(2000);

	armMotors = 40;
	wrist = 0;

	while(SensorValue(driveLeftSensor) < 755)
	{
		drive = 45;
	}

	armMotors = -50;
	stopDrivingClearSensor();
	delay(1000);

	armMotors = 0;
	claw = 127;
	delay(1000);

	claw = 0;
	stopDrivingClearSensor();
	while(SensorValue(driveSensor) > -50)
	{
		drive = -45;
	}

	stopDrivingClearSensor();

	//stopDrivingClearSensor();
	//claw = -127;
	//delay(250);

	//while(SensorValue[driveSensor] > -1000)
	//{
	// drive = -63;
	//}

}



task usercontrol()
{

	while(true)
	{

		joystickControl();

		armCanMove();

		clawCanMove();

		wristCanMove();

		mobileGoalLifter();

		batteryLCDScreen();

		batteryLED();

	}
}
