#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  driveRightSensor, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  armSensor,      sensorQuadEncoder)
#pragma config(Sensor, dgtl11, driveSensor,    sensorQuadEncoder)
#pragma config(Motor,  port1,           mobileL,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           driveR1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveR2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveL1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           driveL2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armR,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           wristMotor,        tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           clawMotor,         tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mobileR,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "definesVariables.h"
#include "functions.h"
#include "autonomousFunctions.h"

void pre_auton()
{

	bStopTasksBetweenModes = true;

}



task autonomous()
{

	//AUTON VOID DECLARATIONS

	//auton10PointRed();
	//auton10PointBlue();
	//auton2point();
	autonSkills();
	//blue20point();






}

task usercontrol()
{

while(true)
{

	joystickControl();

	armCanMove();

	clawCanMove();

	wristCanMove();

	mobileGoalLifter();

	batteryLCDScreen();

	batteryLED();

}
}
