#pragma config(Sensor, dgtl1,  driveSensor,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  armSensor,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  clawSensor,     sensorQuadEncoder)
#pragma config(Motor,  port1,           clawMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightF,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftF,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armMotorL,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotorR,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "definesVariables.h"
#include "functions.h"


void pre_auton()
{

	bStopTasksBetweenModes = true;

}



task autonomous()
{
	while(SensorValue[dgtl1] <3000)
	{

		motor[rightF] = motor[rightB] = 127;
		motor[leftF] = motor[leftB] = 127;

	}
	stopDrivingClearSensor();

	motor[clawmotor] = -127;
	delay(500);

	while(SensorValue(driveSensor) > -2900)
	{
		motor[rightF] = motor[rightB] = -127;
		motor[leftF] = motor[leftB] = -127;
	}
	StopDrivingClearSensor();
}





task usercontrol()
{

	while (true)
	{
		if (vexRT[Btn5U] == 1)
		{
			motor[armMotorL] = 127;
			motor[armMotorR] = 127;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[armMotorL] = -20;
			motor[armMotorR] = -20;
		}
		else
		{
			motor[armMotorL] = 20;
			motor[armMotorR] = 20;
		}

	}
}
